services:
  - type: web
    name: taskmanager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd taskmanager && python manage.py collectstatic --noinput
      cd taskmanager && python manage.py migrate
    startCommand: cd taskmanager && gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: taskmanager_db
    databaseName: taskmanager
    plan: free
    ipAllowList: []